apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: z9g7g328l-nodejs
  janus-idp.io/tekton: z9g7g328l-nodejs
  backstage.io/kubernetes-id: z9g7g328l-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: z9g7g328l-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
